### ISSUE TITLE
Infinite loop issue

### ISSUE THREAD

**Issue by andrejohansson** [matejbucek/Secure_Svelte_With_Keycloak#1]
Hi,

First of all, thank you for writing [your article](https://dev.to/matejbucek/secure-svelte-with-keycloak-42g3) and publishing this example repository!

I'm trying to use this sample in [SvelteKit](https://kit.svelte.dev/) but I'm running into an infinite loop problem (see attached video and source code).

I want to achieve this behavior:

- If I navigate to a secured page (with force login=true), when I'm unauthenticated
    - I should be redirected to my KeyCloak instance to login
    - Then redirected back to the `secure` page (that is, it should remember where I came from) and be logged in
- If I navigate to a secured page while I'm authenticated
    - I should immediately se the contents (no refreshes or similar)

I cannot see in my example what is causing the loop. When I return back from keycloak, the state and code etc is parsed successfully so the init/checkparams method should not need to redirect me again.

Any help or insights is much appreciated!

[Code infinite-loop-issue.zip](https://github.com/matejbucek/Secure_Svelte_With_Keycloak/files/7897227/infinite-loop-issue.zip)

https://user-images.githubusercontent.com/2828428/150134595-59ddc10a-47c7-4434-9b9e-d2b3ceee1754.mp4

**Comment by matejbucek** [comment]
Hi,

Firstly, I am glad that you found that article useful! Thanks.

I took look at it and I found the problem:
* You are not logged in -> Redirect to Keycloak
* After login -> Redirect back to Svelte app
* The page first checks whether the user is logged in or not, before checking the query params. This causes the redirect back to the server.

Solution:
* I made a new branche called _updated_. In here, you can find new code I wrote. It basically does the same thing but in cleaner way and allows us to make use of the _redirectUri_ parameter whilst login (redirect to Keycloak).
* The _forceLogin_ option in _AuthGuard_ automatically takes current URL and gives it to Keycloak. So when you log in, Keycloak will redirect you back to that URL.

Edit:
* The major changed is, that you now have to put your Keycloak configuration into _Registry.ts_ instad of _layout.svelte_.

Hope this solved your issue.

**Comment by andrejohansson** [comment]
Thank you for your feedback, I will have a look at this!
